# Generated by Django 4.2.6 on 2023-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-created'], 'verbose_name': 'Гид', 'verbose_name_plural': 'Гиды'},
        ),
        migrations.AddField(
            model_name='category',
            name='visible_on_main',
            field=models.BooleanField(default=False, verbose_name='Показывать в главной навигации'),
        ),
    ]
