# Generated by Django 4.2.6 on 2023-10-19 05:51

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_guide_competence_remove_guide_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, default='Shakhrisabz', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
