# Generated by Django 4.2.6 on 2023-10-19 06:28

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_restaurant_city_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, default='Shahrisabz', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='39.060366, 66.845915', max_length=63),
        ),
        migrations.AddField(
            model_name='poi',
            name='city',
            field=models.CharField(blank=True, default='Shahrisabz', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='39.060366, 66.845915', max_length=63),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, default='Shahrisabz', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='39.060366, 66.845915', max_length=63),
        ),
    ]
