# Generated by Django 4.2.6 on 2023-10-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_hotel_city_hotel_location_poi_city_poi_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(blank=True, choices=[('Park', 'Парк'), ('Event', 'Мероприятие'), ('LocalCuisine', 'Местная кухня'), ('Souvenir', 'Сувенир')], default='Event', max_length=20, null=True),
        ),
    ]
