# Generated by Django 4.2.6 on 2023-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_poi_poi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(blank=True, choices=[('Park', 'Парк'), ('Event', 'Мероприятие'), ('LocalCuisine', 'Местная кухня'), ('Souvenir', 'Сувенир'), ('Souvenir', 'Достопримечательност')], default='Event', max_length=20, null=True),
        ),
    ]
