# Generated by Django 4.2.6 on 2023-10-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_poi_description_alter_poi_poi_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('case_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.poi')),
            ],
            options={
                'verbose_name': 'Изображение точки интереса',
                'verbose_name_plural': 'Изображения точки интереса',
                'ordering': ['caption'],
            },
        ),
    ]
