# Generated by Django 4.2.6 on 2023-10-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_poiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poiimage',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главное изображение'),
        ),
    ]
