# Generated by Django 4.2.6 on 2023-10-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_poiimage_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта пользователя')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='poi',
            name='city',
            field=models.CharField(blank=True, default='Shahrisabz', max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(blank=True, choices=[('Park', 'Парк'), ('Event', 'Мероприятие'), ('LocalCuisine', 'Местная кухня'), ('Souvenir', 'Сувенир'), ('Souvenir', 'Достопримечательност')], default='Event', max_length=20, null=True, verbose_name='Тип интереса'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
