# Generated by Django 4.2.6 on 2023-10-19 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_subscription_alter_poi_city_alter_poi_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poiimage',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poiimage',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('case_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.hotel')),
            ],
            options={
                'verbose_name': 'Изображение отеля',
                'verbose_name_plural': 'Изображения отеля',
                'ordering': ['caption'],
            },
        ),
    ]
