# Generated by Django 4.2.6 on 2023-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_guide_age_alter_guide_daily_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
