# Generated by Django 4.2.6 on 2023-10-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_buisnessunit_governmentagency_event_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фейбук'),
        ),
        migrations.AddField(
            model_name='guide',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='guide',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Ad', 'Анонс'), ('Happening', 'Событие'), ('Event', 'Мероприятие'), ('Meeting', 'Встреча'), ('Visit', 'Визит')], default='Event', max_length=20, null=True, verbose_name='Тип'),
        ),
    ]
