# Generated by Django 4.2.6 on 2023-10-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_guide_facebook_guide_instagram_guide_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
