# Generated by Django 4.2.6 on 2023-10-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_guide_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание к изображнию'),
        ),
    ]
