# Generated by Django 4.2.6 on 2023-10-20 03:34

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_hotel_address_hotel_notes_alter_hotelimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinstitution',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='city',
            field=models.CharField(blank=True, default='Shahrisabz', max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='39.060366, 66.845915', max_length=63),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
