# Generated by Django 4.2.6 on 2023-10-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_educationinstitution_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='poi_type',
            field=models.CharField(blank=True, choices=[('geology', 'Геологические объекты'), ('ecotourism', 'Объекты экотуризма'), ('info', 'Информационные центры'), ('craft', 'Туристические деревни и ремесла'), ('shrine', 'Cвятыни'), ('historical_places', 'Исторические места'), ('gastronomy', 'Гастрономические центры'), ('others', 'Другие')], default='Event', max_length=20, null=True, verbose_name='Тип интереса'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('News', 'Новость'), ('Blog', 'Запись в блоге'), ('Other', 'Другое')], default='News', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
