# Generated by Django 4.2.6 on 2023-10-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_alter_poi_poi_type_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('News', 'Новость'), ('Blog', 'Запись в блоге'), ('Other', 'Другое')], default='News', max_length=20, null=True, verbose_name='Тип публикации'),
        ),
    ]
