# Generated by Django 4.2.6 on 2023-10-20 09:51

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_alter_post_main_image_alter_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
                ('org_type', models.CharField(blank=True, choices=[('government', 'Госучреждение'), ('business', 'Частный бизнес'), ('education', 'Образовательное учреждение'), ('others', 'Другие')], default='government', max_length=20, null=True, verbose_name='Тип организации')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('city', models.CharField(blank=True, default='Shahrisabz', max_length=255, null=True, verbose_name='Город')),
                ('location', location_field.models.plain.PlainLocationField(default='39.060366, 66.845915', max_length=63)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фейсбук')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграм')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='BuisnessUnit',
        ),
        migrations.DeleteModel(
            name='EducationInstitution',
        ),
        migrations.DeleteModel(
            name='GovernmentAgency',
        ),
    ]
