# Generated by Django 4.2.6 on 2023-10-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_alter_imagegalleryimage_case_attached'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='case_attached',
            new_name='hotel_attached',
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название комнаты')),
                ('price', models.PositiveIntegerField(verbose_name='Цена комнаты')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('hotel_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.hotel')),
            ],
            options={
                'verbose_name': 'Комната отеля',
                'verbose_name_plural': 'Комнаты отеля',
                'ordering': ['-created'],
            },
        ),
    ]
