# Generated by Django 4.2.6 on 2023-10-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0027_alter_restaurant_created_alter_restaurant_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
