# Generated by Django 4.2.6 on 2023-10-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='title',
        ),
        migrations.AddField(
            model_name='transport',
            name='driver',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя водителя'),
        ),
        migrations.AddField(
            model_name='transport',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='transport',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель транспорта'),
        ),
        migrations.AddField(
            model_name='transport',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='transport',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='transport',
            name='transport_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='transport',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
