# Generated by Django 4.2.6 on 2023-10-23 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='records.guide', verbose_name='Гид'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='records.organization', verbose_name='Организатор'),
        ),
    ]
