# Generated by Django 4.2.6 on 2023-10-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_tour_guide_alter_tour_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
    ]
