# Generated by Django 4.2.6 on 2023-10-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_restaurant_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='main_photo',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание к изображнию')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('restaurant_attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.restaurant')),
            ],
            options={
                'verbose_name': 'Изображение ресторана',
                'verbose_name_plural': 'Изображения ресторана',
                'ordering': ['caption'],
            },
        ),
    ]
